/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wakeup_Porcupine */

#ifndef _Included_wakeup_Porcupine
#define _Included_wakeup_Porcupine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wakeup_Porcupine
 * Method:    getFrameLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wakeup_Porcupine_getFrameLength
  (JNIEnv *, jobject);

/*
 * Class:     wakeup_Porcupine
 * Method:    getSampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wakeup_Porcupine_getSampleRate
  (JNIEnv *, jobject);

/*
 * Class:     wakeup_Porcupine
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;F[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_wakeup_Porcupine_init
  (JNIEnv *, jobject, jstring, jstring, jfloat, jobjectArray);

/*
 * Class:     wakeup_Porcupine
 * Method:    process
 * Signature: (J[S)I
 */
JNIEXPORT jint JNICALL Java_wakeup_Porcupine_process
  (JNIEnv *, jobject, jlong, jshortArray);

/*
 * Class:     wakeup_Porcupine
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_wakeup_Porcupine_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
